import type { Todo } from './types/main'

export const openWeatherApiKey = 'bf44bb5b9c31ac9cbd11ad3e14ce81bd'
export const popularCities: Todo[] = [
  {
    name: 'Caracas',
    country: 'VE',
    state: 'Distrito Capital',
    lat: 10.5,
    lon: -66.916664,
  },
  {
    name: 'Tokyo',
    country: 'JP',
    state: 'Tokyo',
    lat: 35.6764,
    lon: 139.65,
  },
  {
    name: 'Madrid',
    country: 'ES',
    state: 'Madrid',
    lat: 40.4165,
    lon: -3.7026,
  },
  {
    name: 'London',
    country: 'GB',
    state: 'London',
    lat: 51.5074,
    lon: -0.1278,
  },
  {
    name: 'Sydney',
    country: 'AU',
    state: 'New South Wales',
    lat: -33.8688197,
    lon: 151.2092955,
  },
]

export const WMOWeatherInterpretationCodes = {
  0: 'Clear sky',
  1: 'Mainly clear',
  2: 'Partly cloudy',
  3: 'Overcast',
  45: 'Fog',
  48: 'Depositing rime fog',
  51: 'Light drizzle',
  53: 'Moderate drizzle',
  55: 'Dense drizzle',
  56: 'Light freezing drizzle',
  57: 'Dense freezing drizzle',
  61: 'Slight rain',
  63: 'Moderate rain',
  65: 'Heavy rain',
  66: 'Light freezing rain',
  67: 'Heavy freezing rain',
  71: 'Slight snowfall',
  73: 'Moderate snowfall',
  75: 'Heavy snowfall',
  77: 'Snow grains',
  80: 'Slight rain showers',
  81: 'Moderate rain showers',
  82: 'Violent rain showers',
  85: 'Slight snow showers',
  86: 'Heavy snow showers',
  95: 'Thunderstorm',
  96: 'Thunderstorm with slight hail',
  99: 'Thunderstorm with heavy hail',
}
